apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy # kubectl deploymenet 이름을 의미함.
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argocd-kube # template metadata labels 이름을 의미함.
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      containers:
      - image: 588738570289.dkr.ecr.ap-northeast-2.amazonaws.com/web-site:cad3589
        name: argocd-kube